server:
  port: 3000

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: ledger-service
  datasource:
    url: jdbc:h2:mem:ledger
    driverClassName: org.h2.Driver
    generate-unique-name: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: true 
    spring.h2.console.settings.web-allow-others: true

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true